import type { AlgorithmMeta, AlgorithmId } from './index'

export const ALGORITHMS: AlgorithmMeta[] = [
  {
    id: 'montecarlo',
    name: 'Montecarlo estándar',
    category: 'Estocástico',
    origin: 'Método de Montecarlo (años 40)',
    description:
      'Estimación estadística de π como el área de un círculo unitario: 4·(puntos dentro)/(puntos totales). Convergencia O(1/√n): unas 3 cifras por cada millón de lanzamientos.',
    convergenceLabel: '≈ 0.60 dígitos por 10⁶ · 4ᴷ',
    runsOnPrecision: false,
    runsOnSamples: true,
    runsOnNeedles: false,
    runsOnHex: false,
    needsSeed: true,
    hasSeries: true,
    defaultPrecision: 100,
    defaultSamples: 10_000_000,
    defaultNeedles: 1_000_000,
    defaultHexDigits: 100,
    maxPrecision: 4,
    maxSamples: 500_000_000,
    maxNeedles: 200_000_000,
    maxHexDigits: 1000,
    estimatedPrecision: '1–4 dígitos (f64)',
  },
  {
    id: 'buffon',
    name: 'Aguja de Buffon',
    category: 'Estocástico',
    origin: 'Conde de Buffon, 1777',
    description:
      'Aguja de longitud L lanzada sobre una retícula de líneas espaciadas L: P(cruza) = 2/π. π ≈ 2n/cruces. Convergencia estocástica O(1/√n), comparable a Montecarlo.',
    convergenceLabel: '≈ 0.60 dígitos por 10⁶ · 4ᴷ',
    runsOnPrecision: false,
    runsOnSamples: false,
    runsOnNeedles: true,
    runsOnHex: false,
    needsSeed: true,
    hasSeries: true,
    defaultPrecision: 100,
    defaultSamples: 10_000_000,
    defaultNeedles: 2_000_000,
    defaultHexDigits: 100,
    maxPrecision: 4,
    maxSamples: 500_000_000,
    maxNeedles: 200_000_000,
    maxHexDigits: 1000,
    estimatedPrecision: '1–4 dígitos (f64)',
  },
  {
    id: 'archimedes',
    name: 'Arquímedes',
    category: 'Iterativo geométrico',
    origin: 'Arquímedes de Siracusa, c. 250 a.C.',
    description:
      'Polígonos inscritos y circunscritos al círculo unitario: los semiperímetros de los 6·2ⁿ-ágonos convergen hacia π aplicando sucesivamente u′ = 2uv/(u+v) y v′ = √(uv).',
    convergenceLabel: '≈ +0.602 dígitos por duplicación (cuadrático débil)',
    runsOnPrecision: true,
    runsOnSamples: false,
    runsOnNeedles: false,
    runsOnHex: false,
    needsSeed: false,
    hasSeries: true,
    defaultPrecision: 100,
    defaultSamples: 10_000_000,
    defaultNeedles: 1_000_000,
    defaultHexDigits: 100,
    maxPrecision: 20_000,
    maxSamples: 500_000_000,
    maxNeedles: 200_000_000,
    maxHexDigits: 1000,
    estimatedPrecision: 'precisión arbitraria',
  },
  {
    id: 'gauss_legendre',
    name: 'Gauss–Legendre',
    category: 'Iterativo geométrico',
    origin: 'Gauss (1818) / Legendre (1825), algoritmo AGM',
    description:
      'Iteración por media aritmético-geométrica (AGM). Cuadrática: cada paso duplica los dígitos correctos. Llegó a usarse para récords (record del mundo en los 80–90).',
    convergenceLabel: '≈ +0.301 dígitos por iteración (cuadrática)',
    runsOnPrecision: true,
    runsOnSamples: false,
    runsOnNeedles: false,
    runsOnHex: false,
    needsSeed: false,
    hasSeries: true,
    defaultPrecision: 100,
    defaultSamples: 10_000_000,
    defaultNeedles: 1_000_000,
    defaultHexDigits: 100,
    maxPrecision: 20_000,
    maxSamples: 500_000_000,
    maxNeedles: 200_000_000,
    maxHexDigits: 1000,
    estimatedPrecision: 'precisión arbitraria',
  },
  {
    id: 'borwein',
    name: 'Borwein (cuártico)',
    category: 'Iterativo geométrico',
    origin: 'Jonathan y Peter Borwein, 1986',
    description:
      'Iteración cuártica: cuatro veces los dígitos correctos por iteración. Utilizado en varios récords mundiales de cálculo de π entre 1986 y 2005.',
    convergenceLabel: '≈ +0.602 dígitos por iteración (cuártica)',
    runsOnPrecision: true,
    runsOnSamples: false,
    runsOnNeedles: false,
    runsOnHex: false,
    needsSeed: false,
    hasSeries: true,
    defaultPrecision: 100,
    defaultSamples: 10_000_000,
    defaultNeedles: 1_000_000,
    defaultHexDigits: 100,
    maxPrecision: 20_000,
    maxSamples: 500_000_000,
    maxNeedles: 200_000_000,
    maxHexDigits: 1000,
    estimatedPrecision: 'precisión arbitraria',
  },
  {
    id: 'ramanujan',
    name: 'Ramanujan (serie 1/π)',
    category: 'Serie (aritmética de alta exactitud)',
    origin: 'Srinivasa Ramanujan, 1914',
    description:
      'Serie convergente con ~8 dígitos correctos por término. Fue la base del récord de Gosper (1985) con 17 millones de dígitos, el primero que superó a Arquímedes.',
    convergenceLabel: '≈ +8 dígitos por término',
    runsOnPrecision: true,
    runsOnSamples: false,
    runsOnNeedles: false,
    runsOnHex: false,
    needsSeed: false,
    hasSeries: true,
    defaultPrecision: 100,
    defaultSamples: 10_000_000,
    defaultNeedles: 1_000_000,
    defaultHexDigits: 100,
    maxPrecision: 20_000,
    maxSamples: 500_000_000,
    maxNeedles: 200_000_000,
    maxHexDigits: 1000,
    estimatedPrecision: 'precisión arbitraria',
  },
  {
    id: 'chudnovsky',
    name: 'Chudnovsky (serie 1/π)',
    category: 'Serie (aritmética de alta exactitud)',
    origin: 'David y Gregory Chudnovsky, 1989',
    description:
      'Serie basada en la identidad j-invariante; ~14.18 dígitos correctos por término. El algoritmo de referencia para los récords actuales (a 2024, el record usa Chudnovsky).',
    convergenceLabel: '≈ +14.18 dígitos por término',
    runsOnPrecision: true,
    runsOnSamples: false,
    runsOnNeedles: false,
    runsOnHex: false,
    needsSeed: false,
    hasSeries: true,
    defaultPrecision: 100,
    defaultSamples: 10_000_000,
    defaultNeedles: 1_000_000,
    defaultHexDigits: 100,
    maxPrecision: 20_000,
    maxSamples: 500_000_000,
    maxNeedles: 200_000_000,
    maxHexDigits: 1000,
    estimatedPrecision: 'precisión arbitraria',
  },
  {
    id: 'bbp',
    name: 'BBP (fórmula spigot)',
    category: 'Spigot (dígito esporádico)',
    origin: 'Bailey–Borwein–Plouffe, 1995',
    description:
      'Fórmula tipo spigot que permite calcular el n-ésimo dígito hexadecimal de π sin conocer los anteriores, en O(n log n). Se usa para verificar récords.',
    convergenceLabel: '1 dígito hex por paso',
    runsOnPrecision: false,
    runsOnSamples: false,
    runsOnNeedles: false,
    runsOnHex: true,
    needsSeed: false,
    hasSeries: false,
    defaultPrecision: 100,
    defaultSamples: 10_000_000,
    defaultNeedles: 1_000_000,
    defaultHexDigits: 100,
    maxPrecision: 4,
    maxSamples: 500_000_000,
    maxNeedles: 200_000_000,
    maxHexDigits: 1000,
    estimatedPrecision: 'n dígitos hexadecimales',
  },
]

export const ALGORITHM_BY_ID: Record<AlgorithmId, AlgorithmMeta> = Object.fromEntries(
  ALGORITHMS.map((a) => [a.id, a]),
) as Record<AlgorithmId, AlgorithmMeta>

export const RUN_FN: Record<AlgorithmId, string> = {
  montecarlo: 'run_montecarlo',
  buffon: 'run_buffon',
  archimedes: 'run_archimedes',
  gauss_legendre: 'run_gauss_legendre',
  borwein: 'run_borwein',
  ramanujan: 'run_ramanujan',
  chudnovsky: 'run_chudnovsky',
  bbp: 'run_bbp',
}

export const SERIES_FN: Partial<Record<AlgorithmId, string>> = {
  montecarlo: 'convergence_montecarlo',
  buffon: 'convergence_buffon',
  archimedes: 'convergence_archimedes',
  gauss_legendre: 'convergence_gauss_legendre',
  borwein: 'convergence_borwein',
  ramanujan: 'convergence_ramanujan',
  chudnovsky: 'convergence_chudnovsky',
}